apiVersion: v1
kind: Pod
metadata:
  name: '{{- printf "%s-%s-%s" .Release.Name .Chart.Name ( .Values.parent | default "base" ) | trunc 63 | trimSuffix "-" -}}'
spec:
  containers:
  - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
    name: '{{ .Chart.Name }}'
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]